steps:
- name: 'gcr.io/cloud-builders/gcloud-slim'
  args: ['source','repos','clone', 'task','src/me','--project=johnbalvin']
- name: 'gcr.io/cloud-builders/go'
  args: ['get','-d','me/backend']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'me/backend']
  env: ['GOPATH=.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/johnbalvin/cern_phoenix_tasks2019', '.']
images: ['gcr.io/johnbalvin/cern_phoenix_tasks2019']  

  
